joyeuse: vibrator: fix wrong "Vibrator.h" file location
this fixes error:

   error: device/xiaomi/joyeuse/vibrator/Android.bp:4:1: module "vendor.qti.hardware.vibrator.impl.xiaomi_joyeuse" variant "android_vendor.30_arm64_armv8-a_shared": module source path "device/xiaoerror: device/xiaomi/joyeuse/vibrator/Android.bp:4:1: module "vendor.qti.hardware.vibrator.impl.xiaomi_joyeuse" variant "android_vendor.30_arm64_armv8-a_shared": module source path "device/xiao
mi/joyeuse/vibrator/include" does not exist
mi/joyeuse/vibrator/include" does not exist